export const language = {
    en : {
        next:"Next",
        search:"Search",
        enter_name:"Enter Your Name",
        continue:"Continue",
        gptPlaceHolder:"What would you like to watch ?",
        play:"Play",
        top_rated:"Top Rated",
        popular:"Popular",
        upcoming:"Upcoming",
        now_playing:"Now Playing",
        sign_in:"Sign In",
        enter_email:"Enter Your email",
        enter_password:"Password",
        sign_up:"Sign Up Now",
        sign_up_main_heading:"Unlimited movies, TV shows and more",
        sign_up_second_heading:"Watch anywhere. Cancel anytime.",
        sign_up_third_heading:"Ready to watch? Enter your email to create or restart your membership.",
        get_started:"Get Started >",
        email_validation_message:"Please enter a valid email address.",
        password_validation_message:"Your password must contain uppercase, lowercase letters & numbers.",
        registration_title:"Finish setting up your account",
        registration_paragraph:"Netflix is personalised for you. Create a password to watch on any device at any time.",
        registration_form_title:"Create a password to start your membership",
        registration_form_heading:"Just a few more steps and you're done! We hate paperwork, too",
        account_created:"Account Created",
        use_email_to_access:"Use this email to access to your account",
        FAQ:"FAQ",
        investor_relations:"Investor Relations",
        privacy:"Privacy",
        speed_test:"Speed Test",
        help_center:"Help center",
        jobs:"Jobs",
        cookie_preferences:"Cookie Preferences",
        legal_notices:"Legal Notices",
        account:"Account",
        ways_to_watch:"Ways to Watch",
        corporate_information:"Corporate Information",
        only_on_netflix:"Only on Netflix",
        media_centre:"Media Centre",
        terms_of_use:"Terms of Use",
        contact_us:"Contact Us",
        question:"Questions? ",
        call:"Call"
    },
    hi :{
       next:"आगे बढ़ें",
       search:"खोज",
       enter_name:"अपना नाम दर्ज करें",
       continue:"जारी रखें",
       gptPlaceHolder:"आप क्या देखना पसंद करेंगे?",
       play:"शुरू करें",
       top_rated:"टॉप रेटेड",
       popular:"लोकप्रिय",
       upcoming:"आगामी",
       now_playing:"चल रही",
       sign_in:"साइन इन",
       enter_email:"अपना ईमेल दर्ज करें",
       enter_password:"पासवर्ड",
       sign_up:"साइन अप करें",
       sign_up_main_heading:"अनलिमिटेड फ़िल्में, टीवी शो के साथ भी बहुत कुछ",
       sign_up_second_heading:"जहां चाहें देखें. जब चाहें कैंसल करें.",
       sign_up_third_heading:"देखने के लिए तैयार हैं? अपनी मेंबरशिप बनाने या रीस्टार्ट करने के लिए",
       get_started:"शुरू करें >",
       email_validation_message:"कृपया एक मान्य ईमेल दर्ज करें !",
       password_validation_message:"कृपया एक वैध पासवर्ड दर्ज करें।",
       registration_title:"अपनी अकाउंट सेटिंग पूरी करें",
       registration_paragraph:"Netflix को आपके लिए पर्सनलाईज़ किया गया है. किसी भी समय किसी भी डिवाइस पर देखने के लिए पासवर्ड बनाएं.",
       registration_form_title:"अपनी सदस्यता शुरू करने के लिए पासवर्ड बनाएं",
       registration_form_heading:"बस कुछ ही कदम और बचे हैं, और आप तैयार हैं! हमें भी कागजी काम पसंद नहीं।",
       account_created:"खाता बनाया गया",
       use_email_to_access:"अपने खाते तक पहुंचने के लिए इस ईमेल का उपयोग करें",
       FAQ:"अक्सर पूछे जाने वाले प्रश्न",
       investor_relations:"इन्वेस्टर रिलेशंस",
       privacy:"प्राइवेसी",
       speed_test:"स्पीड टेस्ट",
       help_center:"हेल्प सेंटर",
       jobs:"नौकरियाँ",
       cookie_preferences:"कुकी प्राथमिकताएँ",
       legal_notices:"कानूनी नोटिस",
       account:"खाता",
       ways_to_watch:"देखने के तरीके",
       corporate_information:"कॉर्पोरेट जानकारी",
       only_on_netflix:"केवल नेटफ्लिक्स पर",
       media_centre:"मीडिया केंद्र",
       terms_of_use:"उपयोग की शर्तें",
       contact_us:"संपर्क करें",
       question:" प्रश्न? ",
       call:"कॉल"
    } 
}